import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * 构建完成后把插件产物拷贝到目标 Obsidian 库的插件目录（便于本地开发）。
 * 目标路径来源（按优先级）：
 *   1. 环境变量 XGKB_PLUGIN_DEPLOY_DIR
 *   2. 仓库根的 .deploy-target 文件（已 gitignore，各自机器配置，不进仓库）
 * 两者都没有则跳过拷贝。仓库内不保留任何本机绝对路径。
 */
function resolveDeployDir() {
	if (process.env.XGKB_PLUGIN_DEPLOY_DIR) return process.env.XGKB_PLUGIN_DEPLOY_DIR.trim();
	try {
		return fs.readFileSync(".deploy-target", "utf8").trim();
	} catch {
		return "";
	}
}

const DEPLOY_DIR = resolveDeployDir();

const DEPLOY_FILES = ["main.js", "manifest.json", "styles.css"];

function deployArtifacts() {
	if (!DEPLOY_DIR) return;
	try {
		fs.mkdirSync(DEPLOY_DIR, { recursive: true });
		const copied = [];
		for (const file of DEPLOY_FILES) {
			if (!fs.existsSync(file)) continue;
			fs.copyFileSync(file, path.join(DEPLOY_DIR, file));
			copied.push(file);
		}
		console.log(`[deploy] 已拷贝 ${copied.join(", ")} → ${DEPLOY_DIR}`);
	} catch (e) {
		console.error(`[deploy] 拷贝失败 → ${DEPLOY_DIR}:`, e instanceof Error ? e.message : e);
	}
}

/** esbuild 插件：每次构建结束（含 watch 重建）后部署产物 */
const deployPlugin = {
	name: "deploy-plugin",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			deployArtifacts();
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [deployPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
