/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => XgkbSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/constants.ts
var DEFAULT_SETTINGS = {
  appKey: "",
  serverUrl: "https://sg-al-cwork-web.mediportal.com.cn/open-api/",
  syncFolder: "",
  // 空=同步整个 Vault
  targetFolderName: "Obsidian",
  syncDirection: "bidirectional",
  autoSyncInterval: 0
  // 默认关闭
};
var API_PATHS = {
  getChildFiles: "document-database/file/getChildFiles",
  listDescendantFiles: "document-database/file/listDescendantFiles",
  listChanges: "document-database/file/listChanges",
  batchGetMeta: "document-database/file/batchGetMeta",
  createFolder: "document-database/file/createFolder",
  getDownloadInfo: "document-database/file/getDownloadInfo",
  getFileContent: "document-database/file/getFileContent",
  getFullFileContent: "document-database/file/getFullFileContent",
  uploadContent: "document-database/file/uploadContent",
  searchFile: "document-database/file/searchFile",
  getLevel1Folders: "document-database/file/getLevel1Folders",
  deleteFile: "document-database/file/deleteFile",
  getVersionList: "document-database/file/getVersionList",
  getPersonalProjectId: "document-database/project/personal/getProjectId",
  getProjectList: "document-database/project/list",
  /** 见《03-AI与纯文本高速通道》4.15，建议单次不超过 10 个文件 */
  batchGetContent: "document-database/ai/batchGetContent"
};
var BATCH_GET_CONTENT_MAX = 10;
var BATCH_GET_META_MAX = 50;
var CHANGES_SAFETY_WINDOW_MS = 5e3;
var DB_NAME = "xgkb-sync-state";
var DB_VERSION = 1;
var DB_STORE_NAME = "syncState";
var MAX_RETRIES = 3;
var RETRY_BASE_DELAY_MS = 1e3;
var MTIME_TOLERANCE_MS = 1e3;
function cleanContent(raw) {
  return raw.replace(/\n*Page \d+ of \d+\s*$/, "").trimEnd() + "\n";
}

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/xgkbApi.ts
var import_obsidian = require("obsidian");
var XgkbApi = class {
  constructor(serverUrl, appKey) {
    this.serverUrl = serverUrl.endsWith("/") ? serverUrl : serverUrl + "/";
    this.appKey = appKey;
  }
  async delay(ms) {
    return new Promise((resolve) => window.setTimeout(resolve, ms));
  }
  async request(method, apiPath, params) {
    var _a, _b;
    const baseUrl = this.serverUrl + apiPath;
    const options = {
      url: baseUrl,
      method,
      headers: {
        "Content-Type": "application/json",
        appKey: this.appKey
      }
    };
    if (method === "GET" && params) {
      const qs = Object.entries(params).filter(([, v]) => v !== void 0 && v !== null).map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`).join("&");
      options.url = qs ? `${baseUrl}?${qs}` : baseUrl;
    } else if (method === "POST" && params) {
      options.url = baseUrl;
      options.body = JSON.stringify(params);
    } else {
      options.url = baseUrl;
    }
    let lastError = "";
    for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
      try {
        if (attempt > 0)
          await this.delay(RETRY_BASE_DELAY_MS * Math.pow(2, attempt));
        const resp = await (0, import_obsidian.requestUrl)(options);
        const result = resp.json;
        if (result.resultCode !== 1) {
          if (result.resultCode === 401) {
            return { ok: false, error: `\u8BA4\u8BC1\u5931\u8D25(401): ${(_a = result.resultMsg) != null ? _a : "Unknown error"}` };
          }
          return { ok: false, error: `API error ${result.resultCode}: ${(_b = result.resultMsg) != null ? _b : "Unknown error"}` };
        }
        return { ok: true, value: result.data };
      } catch (e) {
        lastError = e instanceof Error ? e.message : String(e);
      }
    }
    return { ok: false, error: `\u8BF7\u6C42\u5931\u8D25(\u91CD\u8BD5${MAX_RETRIES}\u6B21): ${lastError}` };
  }
  // ==================== 空间/目录 ====================
  /** 获取个人知识库空间 ID */
  async getPersonalProjectId() {
    const r = await this.request("GET", API_PATHS.getPersonalProjectId);
    if (!r.ok)
      return r;
    return { ok: true, value: String(r.value) };
  }
  /** 获取一级目录 */
  async getLevel1Folders(projectId) {
    return this.request("GET", API_PATHS.getLevel1Folders, { projectId });
  }
  /** 浏览子目录/文件 */
  async getChildFiles(parentId, type) {
    const params = { parentId };
    if (type !== void 0)
      params.type = type;
    return this.request("GET", API_PATHS.getChildFiles, params);
  }
  /** 子树扁平列举（4.21） */
  async listDescendantFiles(params) {
    return this.request("GET", API_PATHS.listDescendantFiles, params);
  }
  /** 增量变更列表（4.22） */
  async listChanges(params) {
    return this.request("GET", API_PATHS.listChanges, params);
  }
  /** 搜索文件 */
  async searchFile(nameKey) {
    const r = await this.request(
      "GET",
      API_PATHS.searchFile,
      { nameKey }
    );
    if (!r.ok)
      return r;
    return { ok: true, value: r.value.files || [] };
  }
  // ==================== 文件内容 ====================
  /** 读取文件全文（所写即所读，双写缓存已跑通） */
  async getFullFileContent(fileId) {
    return this.request("GET", API_PATHS.getFullFileContent, { fileId });
  }
  /**
   * 批量获取多个文件的提纯全文（4.15）
   * 不限于个人空间，凭 fileId 与 appKey 权限拉取；建议单次 ≤10 个文件。
   */
  async batchGetContent(files) {
    return this.request("POST", API_PATHS.batchGetContent, { files });
  }
  /** 批量元数据（4.23） */
  async batchGetMeta(fileIds, projectId) {
    return this.request("POST", API_PATHS.batchGetMeta, { fileIds, projectId });
  }
  /**
   * 上传/更新文件（轻量高速通道）
   *
   * 新建模式：不传 updateFileId
   * 更新模式：传 updateFileId → 自动创建新版本
   */
  async uploadContent(params) {
    return this.request(
      "POST",
      API_PATHS.uploadContent,
      params
    );
  }
  /** 删除文件 */
  async deleteFile(fileId) {
    const r = await this.request("POST", API_PATHS.deleteFile, { fileId });
    if (!r.ok)
      return r;
    return { ok: true, value: true };
  }
  /** 显式创建空目录（4.24） */
  async createFolder(params) {
    const r = await this.request("POST", API_PATHS.createFolder, params);
    if (!r.ok)
      return r;
    return { ok: true, value: String(r.value) };
  }
  /** 获取版本列表（调试用） */
  async getVersionList(fileId) {
    return this.request("GET", API_PATHS.getVersionList, { fileId });
  }
};

// src/fsLocal.ts
var Obsidian = __toESM(require("obsidian"));

// src/pathSanitize.ts
var ILLEGAL_IN_SEGMENT = /[*"<>:|?\\]/g;
function sanitizePathSegment(segment) {
  return segment.replace(ILLEGAL_IN_SEGMENT, "-");
}
function sanitizeRelativePath(relativePath) {
  if (!relativePath)
    return relativePath;
  return relativePath.split("/").map((seg) => sanitizePathSegment(seg)).join("/");
}

// src/fsLocal.ts
var FsLocal = class {
  constructor(app, syncFolder) {
    this.app = app;
    this.basePath = syncFolder ? this.normalize(syncFolder) : app.vault.getRoot().path;
  }
  normalize(p) {
    return p.replace(/\\/g, "/").replace(/\/+/g, "/");
  }
  /** 列出 syncFolder 下所有 .md 文件（递归） */
  listFiles() {
    const folder = this.app.vault.getAbstractFileByPath(this.basePath);
    if (!folder || !(folder instanceof Obsidian.TFolder))
      return [];
    const entries = [];
    this.collectMd(folder, entries, "");
    return entries;
  }
  collectMd(folder, entries, prefix) {
    for (const child of folder.children) {
      if (child instanceof Obsidian.TFile) {
        if (child.extension === "md" && !child.name.includes("_conflict_")) {
          const seg = sanitizePathSegment(child.name);
          const relativePath = prefix ? `${prefix}/${seg}` : seg;
          entries.push({
            path: relativePath,
            name: child.name,
            mtime: child.stat.mtime,
            size: child.stat.size
          });
        }
      } else if (child instanceof Obsidian.TFolder) {
        const seg = sanitizePathSegment(child.name);
        const subPrefix = prefix ? `${prefix}/${seg}` : seg;
        if (child.name.startsWith("."))
          continue;
        this.collectMd(child, entries, subPrefix);
      }
    }
  }
  /** 读取文件内容 */
  async readFile(relativePath) {
    const fullPath = this.resolve(relativePath);
    const file = this.app.vault.getAbstractFileByPath(fullPath);
    if (!file || !(file instanceof Obsidian.TFile)) {
      throw new Error(`\u6587\u4EF6\u4E0D\u5B58\u5728: ${fullPath}`);
    }
    return this.app.vault.read(file);
  }
  /** 写入文件（自动创建目录） */
  async writeFile(relativePath, content) {
    const fullPath = this.resolve(relativePath);
    await this.ensureFolder(fullPath);
    const existing = this.app.vault.getAbstractFileByPath(fullPath);
    if (existing instanceof Obsidian.TFile) {
      await this.app.vault.modify(existing, content);
    } else {
      await this.app.vault.create(fullPath, content);
    }
    const file = this.app.vault.getAbstractFileByPath(fullPath);
    if (!(file instanceof Obsidian.TFile)) {
      throw new Error(`\u5199\u5165\u540E\u65E0\u6CD5\u8BFB\u53D6\u6587\u4EF6\u72B6\u6001: ${fullPath}`);
    }
    return file.stat.mtime;
  }
  /** 删除文件（走 Vault 回收站） */
  async trashFile(relativePath) {
    const fullPath = this.resolve(relativePath);
    const file = this.app.vault.getAbstractFileByPath(fullPath);
    if (file instanceof Obsidian.TFile) {
      await this.app.fileManager.trashFile(file);
    }
  }
  /** 获取文件的 mtime */
  getMtime(relativePath) {
    const fullPath = this.resolve(relativePath);
    const file = this.app.vault.getAbstractFileByPath(fullPath);
    if (file instanceof Obsidian.TFile)
      return file.stat.mtime;
    return null;
  }
  resolve(relativePath) {
    const safe = sanitizeRelativePath(this.normalize(relativePath));
    const root = this.app.vault.getRoot().path;
    if (this.basePath === root)
      return safe;
    return `${this.basePath}/${safe}`;
  }
  async ensureFolder(fullPath) {
    const parts = fullPath.split("/");
    if (parts.length <= 1)
      return;
    const folderParts = parts.slice(0, -1);
    let current = "";
    for (const part of folderParts) {
      current = current ? `${current}/${part}` : part;
      const normalized = this.normalize(current);
      if (!this.app.vault.getAbstractFileByPath(normalized)) {
        await this.app.vault.createFolder(normalized);
      }
    }
  }
};

// src/fsXgkb.ts
var FsXgkb = class {
  constructor(api, targetFolderName) {
    this.api = api;
    this.targetFolderName = targetFolderName;
    this.rootId = null;
    this.projectId = null;
  }
  getRootId() {
    return this.rootId;
  }
  getProjectId() {
    return this.projectId;
  }
  /**
   * 初始化：获取 Obsidian 文件夹 ID
   * 如果不存在，使用 createFolder 显式创建
   */
  async init() {
    const projectResult = await this.api.getPersonalProjectId();
    if (!projectResult.ok) {
      return { ok: false, error: `\u83B7\u53D6 projectId \u5931\u8D25: ${projectResult.error}` };
    }
    const projectId = projectResult.value;
    this.projectId = projectId;
    console.debug(`[XGKB Sync] init: projectId=${projectId}`);
    const foldersResult = await this.api.getLevel1Folders(projectId);
    if (!foldersResult.ok) {
      return { ok: false, error: `\u83B7\u53D6\u76EE\u5F55\u5217\u8868\u5931\u8D25: ${foldersResult.error}` };
    }
    const folders = foldersResult.value || [];
    const target = folders.find((f) => f.name === this.targetFolderName && f.type === 1);
    if (target) {
      this.rootId = target.id;
      console.debug(`[XGKB Sync] init: \u627E\u5230\u540C\u6B65\u6839\u76EE\u5F55 "${this.targetFolderName}" rootId=${target.id}`);
      return { ok: true, value: target.id };
    }
    console.debug(`[XGKB Sync] init: \u672A\u627E\u5230 "${this.targetFolderName}"\uFF0C\u8C03\u7528 createFolder \u65B0\u5EFA...`);
    const createResult = await this.api.createFolder({
      projectId,
      parentId: "0",
      name: this.targetFolderName
    });
    if (!createResult.ok) {
      return { ok: false, error: `\u521B\u5EFA Obsidian \u76EE\u5F55\u5931\u8D25: ${createResult.error}` };
    }
    this.rootId = createResult.value;
    console.debug(`[XGKB Sync] init: \u65B0\u5EFA\u540C\u6B65\u6839\u76EE\u5F55 "${this.targetFolderName}" rootId=${createResult.value}`);
    return { ok: true, value: createResult.value };
  }
  /**
   * 通过 4.21 扁平列举同步根目录下所有 .md 文件
   */
  async listFiles() {
    var _a;
    if (!this.rootId)
      return { ok: false, error: "\u672A\u521D\u59CB\u5316" };
    const entries = [];
    let cursor;
    let page = 0;
    do {
      page++;
      const r = await this.api.listDescendantFiles({
        rootFileId: this.rootId,
        projectId: this.projectId || void 0,
        suffix: "md",
        limit: 500,
        cursor,
        includePath: true
      });
      if (!r.ok)
        return { ok: false, error: r.error };
      const pageItems = r.value.files || [];
      console.debug(`[XGKB Sync] listDescendantFiles \u7B2C${page}\u9875: \u8FD4\u56DE ${pageItems.length} \u6761\uFF0CnextCursor=${(_a = r.value.nextCursor) != null ? _a : "null"}`);
      for (const item of pageItems) {
        const rawPath = item.relativePath || item.name;
        const safePath = rawPath.split("/").filter(Boolean).map((seg) => sanitizePathSegment(seg)).join("/");
        if (!safePath.endsWith(".md"))
          continue;
        entries.push({
          path: safePath,
          name: item.name,
          mtime: item.updateTime || 0,
          size: item.size,
          xgkbFileId: String(item.fileId),
          xgkbFolderId: item.parentId != null ? String(item.parentId) : ""
        });
      }
      cursor = r.value.nextCursor || void 0;
    } while (cursor);
    console.debug(`[XGKB Sync] listDescendantFiles \u5B8C\u6210: \u5171 ${entries.length} \u4E2A .md \u6587\u4EF6\uFF0C${page} \u9875`);
    return { ok: true, value: entries };
  }
  /**
   * 读取云端文件内容（使用 getFullFileContent，所写即所读）
   */
  async readFile(fileId) {
    const result = await this.api.getFullFileContent(fileId);
    if (!result.ok)
      return result;
    return { ok: true, value: cleanContent(result.value) };
  }
  /**
   * 批量预取全文（4.15 `batchGetContent`）。
   * 不限个人空间，凭 fileId 与 appKey 权限拉取；建议每批不超过 {@link BATCH_GET_CONTENT_MAX} 个。
   * 若某项未命中或非 success，调用方应回退 {@link readFile}。
   */
  async readFilesBatch(fileIds) {
    var _a, _b;
    const out = /* @__PURE__ */ new Map();
    const unique = [...new Set(fileIds.filter(Boolean))];
    for (let i = 0; i < unique.length; i += BATCH_GET_CONTENT_MAX) {
      const chunk = unique.slice(i, i + BATCH_GET_CONTENT_MAX);
      const r = await this.api.batchGetContent(chunk.map((fileId) => ({ fileId })));
      if (!r.ok) {
        console.warn("[XGKB Sync] batchGetContent \u5931\u8D25\uFF0C\u672A\u547D\u4E2D\u9879\u5C06\u56DE\u9000\u5355\u6587\u4EF6\u62C9\u53D6:", r.error);
        continue;
      }
      let mergedThisChunk = 0;
      for (const row of r.value || []) {
        const id = String(row.fileId);
        if (row.status === "success" && row.content != null) {
          out.set(id, cleanContent(row.content));
          mergedThisChunk++;
        }
      }
      console.debug(
        `[XGKB Sync] batchGetContent \u5DF2\u8FD4\u56DE: \u672C\u6279 ${chunk.length} \u4E2A fileId\uFF0C\u63A5\u53E3\u54CD\u5E94 ${(_b = (_a = r.value) == null ? void 0 : _a.length) != null ? _b : 0} \u6761\uFF0C\u53EF\u7528\u6B63\u6587 ${mergedThisChunk} \u6761`
      );
    }
    return out;
  }
  /**
   * 上传新文件（使用 uploadContent）
   * @param relativePath 相对路径（如 "日常学习/笔记.md"）
   * @param content Markdown 内容
   * @returns fileId 与 folderId（folderId 用于状态库，支撑增量同步路径缓存）
   */
  async createFile(relativePath, content) {
    const lastSlash = relativePath.lastIndexOf("/");
    const folderPath = lastSlash > 0 ? relativePath.substring(0, lastSlash) : "";
    const fileName = lastSlash > 0 ? relativePath.substring(lastSlash + 1) : relativePath;
    const folderName = folderPath ? `${this.targetFolderName}/${folderPath}` : this.targetFolderName;
    const result = await this.api.uploadContent({
      content,
      fileName,
      fileSuffix: "md",
      folderName
    });
    if (!result.ok)
      return { ok: false, error: `\u4E0A\u4F20\u5931\u8D25: ${result.error}` };
    const data = result.value;
    return {
      ok: true,
      value: {
        fileId: String(data.fileId),
        folderId: data.folderId != null ? String(data.folderId) : ""
      }
    };
  }
  /**
   * 更新已有文件（使用 uploadContent + updateFileId）
   */
  async updateFile(fileId, fileName, content) {
    const result = await this.api.uploadContent({
      content,
      fileName,
      fileSuffix: "md",
      updateFileId: fileId,
      versionRemark: "XGKB Sync plugin update"
    });
    if (!result.ok)
      return { ok: false, error: `\u66F4\u65B0\u5931\u8D25: ${result.error}` };
    const data = result.value;
    return { ok: true, value: data.fileId };
  }
  /** 删除云端文件 */
  async deleteFile(fileId) {
    return this.api.deleteFile(fileId).then(
      (r) => r.ok ? { ok: true, value: void 0 } : r
    );
  }
  /**
   * 拉取所有增量变更（4.22）自动翻页，直到 nextCursor 为空。
   * @param since 毫秒时间戳（已含安全回拨）
   */
  async listAllChanges(since) {
    var _a, _b, _c;
    if (!this.rootId || !this.projectId)
      return { ok: false, error: "\u672A\u521D\u59CB\u5316" };
    const sinceStr = new Date(since).toLocaleString("zh-CN");
    console.debug(`[XGKB Sync] listChanges: since=${since} (${sinceStr}), rootId=${this.rootId}`);
    const allItems = [];
    let cursor;
    let serverTime;
    let page = 0;
    do {
      page++;
      const r = await this.api.listChanges({
        projectId: this.projectId,
        rootFileId: this.rootId,
        since: cursor ? void 0 : since,
        cursor,
        limit: 200
      });
      if (!r.ok)
        return { ok: false, error: r.error };
      const pageItems = r.value.items || [];
      console.debug(`[XGKB Sync] listChanges \u7B2C${page}\u9875: ${pageItems.length} \u6761\uFF0CnextCursor=${(_a = r.value.nextCursor) != null ? _a : "null"}\uFF0CserverTime=${(_b = r.value.serverTime) != null ? _b : "-"}`);
      allItems.push(...pageItems);
      serverTime = (_c = r.value.serverTime) != null ? _c : serverTime;
      cursor = r.value.nextCursor || void 0;
    } while (cursor);
    const upsertCount = allItems.filter((i) => i.event !== "delete").length;
    const deleteCount = allItems.filter((i) => i.event === "delete").length;
    console.debug(`[XGKB Sync] listChanges \u5B8C\u6210: \u5171 ${allItems.length} \u6761 (upsert:${upsertCount} delete:${deleteCount})\uFF0CserverTime=${serverTime}`);
    return { ok: true, value: { items: allItems, serverTime } };
  }
  /**
   * 分批调用 batchGetMeta（4.23），返回 fileId → 元数据的 Map。
   * 未返回的 fileId（不存在/无权限）不在 Map 中，调用方按删除处理。
   */
  async batchGetMetaAll(fileIds) {
    var _a, _b;
    const out = /* @__PURE__ */ new Map();
    const unique = [...new Set(fileIds.filter(Boolean))];
    console.debug(`[XGKB Sync] batchGetMeta: \u8BF7\u6C42 ${unique.length} \u4E2A fileId\uFF0C\u5206 ${Math.ceil(unique.length / BATCH_GET_META_MAX)} \u6279`);
    for (let i = 0; i < unique.length; i += BATCH_GET_META_MAX) {
      const chunk = unique.slice(i, i + BATCH_GET_META_MAX);
      const r = await this.api.batchGetMeta(chunk, this.projectId || void 0);
      if (!r.ok) {
        console.warn("[XGKB Sync] batchGetMeta \u5931\u8D25:", r.error);
        continue;
      }
      let deletedCount = 0;
      for (const item of r.value || []) {
        out.set(String(item.fileId), item);
        if (item.deleted)
          deletedCount++;
      }
      console.debug(`[XGKB Sync] batchGetMeta \u6279\u6B21[${Math.floor(i / BATCH_GET_META_MAX) + 1}]: \u8BF7\u6C42 ${chunk.length} \u4E2A\uFF0C\u8FD4\u56DE ${(_b = (_a = r.value) == null ? void 0 : _a.length) != null ? _b : 0} \u6761\uFF08\u5176\u4E2D deleted:${deletedCount}\uFF09`);
    }
    const missingCount = unique.length - out.size;
    console.debug(`[XGKB Sync] batchGetMeta \u5B8C\u6210: \u547D\u4E2D ${out.size} \u4E2A\uFF0C\u672A\u8FD4\u56DE/\u65E0\u6743\u9650 ${missingCount} \u4E2A\uFF08\u5C06\u89C6\u4E3A\u8FDC\u7AEF\u5220\u9664\uFF09`);
    return out;
  }
};

// src/settings.ts
var XgkbPluginSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("App key").setDesc("\u7384\u5173\u77E5\u8BC6\u5E93 API \u5BC6\u94A5").addText(
      (text) => text.setPlaceholder("Enter app key").setValue(this.plugin.settings.appKey).onChange(async (value) => {
        this.plugin.settings.appKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Server URL").setDesc("\u7384\u5173\u77E5\u8BC6\u5E93 API \u5730\u5740").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.serverUrl).setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
        this.plugin.settings.serverUrl = value || DEFAULT_SETTINGS.serverUrl;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Sync folder").setDesc("Obsidian \u4E2D\u7528\u4E8E\u540C\u6B65\u7684\u6587\u4EF6\u5939\u8DEF\u5F84\uFF08\u7A7A = \u540C\u6B65\u6574\u4E2A vault\uFF09").addText(
      (text) => text.setPlaceholder("Example: notes").setValue(this.plugin.settings.syncFolder).onChange(async (value) => {
        this.plugin.settings.syncFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Cloud target folder").setDesc("\u7384\u5173\u77E5\u8BC6\u5E93\u4E2D\u76EE\u6807\u6587\u4EF6\u5939\u540D\u79F0").addText(
      (text) => text.setPlaceholder("Obsidian").setValue(this.plugin.settings.targetFolderName).onChange(async (value) => {
        this.plugin.settings.targetFolderName = value || "Obsidian";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Sync direction").setDesc("\u53CC\u5411\u540C\u6B65 / \u4EC5\u63A8\u9001 / \u4EC5\u62C9\u53D6").addDropdown(
      (dropdown) => dropdown.addOption("bidirectional", "Bidirectional").addOption("push", "Push only").addOption("pull", "Pull only").setValue(this.plugin.settings.syncDirection).onChange(async (value) => {
        this.plugin.settings.syncDirection = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Automatic sync interval").setDesc("\u5B9A\u671F\u81EA\u52A8\u6267\u884C\u540C\u6B65\uFF0C\u5173\u95ED\u5219\u4EC5\u624B\u52A8\u89E6\u53D1").addDropdown(
      (dropdown) => dropdown.addOption("0", "Off (manual sync)").addOption("5", "Every 5 minutes").addOption("10", "Every 10 minutes").addOption("30", "Every 30 minutes").addOption("60", "Every hour").addOption("120", "Every 2 hours").setValue(String(this.plugin.settings.autoSyncInterval)).onChange(async (value) => {
        this.plugin.settings.autoSyncInterval = Number(value);
        await this.plugin.saveSettings();
        this.plugin.scheduleAutoSync();
      })
    );
    const btnGroup = containerEl.createDiv({ cls: "xgkb-settings-button-group" });
    const testBtn = btnGroup.createEl("button", { text: "Test connection", cls: "mod-cta" });
    testBtn.addEventListener("click", () => {
      void this.testConnection();
    });
    const debugBtn = btnGroup.createEl("button", { text: "Diagnostics" });
    debugBtn.addEventListener("click", () => {
      void this.debugSync();
    });
  }
  async testConnection() {
    const { appKey, serverUrl, targetFolderName } = this.plugin.settings;
    if (!appKey) {
      new import_obsidian2.Notice("Enter app key first");
      return;
    }
    new import_obsidian2.Notice("\u6D4B\u8BD5\u8FDE\u63A5\u4E2D...");
    const api = new XgkbApi(serverUrl, appKey);
    const projectIdResult = await api.getPersonalProjectId();
    if (!projectIdResult.ok) {
      new import_obsidian2.Notice(`\u274C \u8FDE\u63A5\u5931\u8D25: ${projectIdResult.error}`, 5e3);
      return;
    }
    const foldersResult = await api.getLevel1Folders(projectIdResult.value);
    if (!foldersResult.ok) {
      new import_obsidian2.Notice(`\u274C \u83B7\u53D6\u76EE\u5F55\u5931\u8D25: ${foldersResult.error}`, 5e3);
      return;
    }
    const folders = foldersResult.value || [];
    const target = folders.find((f) => f.name === targetFolderName && f.type === 1);
    if (!target) {
      const names = folders.map((f) => f.name).join(", ");
      new import_obsidian2.Notice(`\u274C \u76EE\u5F55 "${targetFolderName}" \u4E0D\u5B58\u5728\u3002\u73B0\u6709: ${names || "(\u7A7A)"}`, 8e3);
      return;
    }
    const filesResult = await api.getChildFiles(target.id);
    if (!filesResult.ok) {
      new import_obsidian2.Notice(`\u274C \u76EE\u5F55\u8BBF\u95EE\u5931\u8D25: ${filesResult.error}`, 5e3);
      return;
    }
    const items = filesResult.value || [];
    const mdCount = items.filter((f) => f.type === 2 && f.suffix === "md").length;
    const folderCount = items.filter((f) => f.type === 1).length;
    new import_obsidian2.Notice(`\u2705 \u8FDE\u63A5\u6210\u529F\uFF01"${targetFolderName}" \u542B ${mdCount} \u4E2A .md \u6587\u4EF6\u3001${folderCount} \u4E2A\u5B50\u6587\u4EF6\u5939`, 5e3);
  }
  async debugSync() {
    const { appKey, serverUrl, targetFolderName, syncFolder, syncDirection } = this.plugin.settings;
    if (!appKey) {
      new import_obsidian2.Notice("Enter app key first");
      return;
    }
    new import_obsidian2.Notice("\u8BCA\u65AD\u4E2D...");
    const api = new XgkbApi(serverUrl, appKey);
    const lines = [`=== XGKB Sync \u8BCA\u65AD ===
`];
    lines.push(`\u540C\u6B65\u65B9\u5411: ${syncDirection}`);
    lines.push(`SyncFolder: "${syncFolder || "(\u6574\u4E2AVault)"}"`);
    lines.push(`TargetFolder: "${targetFolderName}"
`);
    try {
      const fsLocal = new FsLocal(this.plugin.app, syncFolder);
      const fsXgkb = new FsXgkb(api, targetFolderName);
      const localFiles = fsLocal.listFiles();
      lines.push(`\u672C\u5730 .md \u6587\u4EF6: ${localFiles.length} \u4E2A`);
      for (const f of localFiles.slice(0, 10)) {
        lines.push(`  \u{1F4C4} ${f.path}  (${new Date(f.mtime).toLocaleString()})`);
      }
      if (localFiles.length > 10)
        lines.push(`  ... \u8FD8\u6709 ${localFiles.length - 10} \u4E2A`);
      const initResult = await fsXgkb.init();
      if (!initResult.ok) {
        lines.push(`
\u274C \u4E91\u7AEF\u521D\u59CB\u5316\u5931\u8D25: ${initResult.error}`);
      } else {
        const remoteResult = await fsXgkb.listFiles();
        if (!remoteResult.ok) {
          lines.push(`
\u274C \u83B7\u53D6\u4E91\u7AEF\u6587\u4EF6\u5931\u8D25: ${remoteResult.error}`);
        } else {
          const remoteFiles = remoteResult.value;
          lines.push(`
\u4E91\u7AEF .md \u6587\u4EF6: ${remoteFiles.length} \u4E2A`);
          for (const f of remoteFiles.slice(0, 10)) {
            lines.push(`  \u2601\uFE0F ${f.path}  (${new Date(f.mtime).toLocaleString()})`);
          }
          if (remoteFiles.length > 10)
            lines.push(`  ... \u8FD8\u6709 ${remoteFiles.length - 10} \u4E2A`);
          const localPaths = new Set(localFiles.map((f) => f.path));
          const remotePaths = new Set(remoteFiles.map((f) => f.path));
          const localOnly = [...localPaths].filter((p) => !remotePaths.has(p));
          const remoteOnly = [...remotePaths].filter((p) => !localPaths.has(p));
          const both = [...localPaths].filter((p) => remotePaths.has(p));
          lines.push(`
=== \u5DEE\u5F02\u5206\u6790 ===`);
          lines.push(`\u4EC5\u672C\u5730: ${localOnly.length}  \u4EC5\u4E91\u7AEF: ${remoteOnly.length}  \u4E24\u7AEF\u90FD\u6709: ${both.length}`);
          if (localOnly.length > 0) {
            lines.push(`
\u5C06\u4E0A\u4F20 (${localOnly.length}):`);
            for (const p of localOnly.slice(0, 10))
              lines.push(`  \u2B06 ${p}`);
          }
          if (remoteOnly.length > 0) {
            lines.push(`
\u5C06\u4E0B\u8F7D (${remoteOnly.length}):`);
            for (const p of remoteOnly.slice(0, 10))
              lines.push(`  \u2B07 ${p}`);
          }
        }
      }
      lines.push(`
\u8BCA\u65AD\u5B8C\u6210\u3002`);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      lines.push(`
\u8BCA\u65AD\u5F02\u5E38: ${message}`);
    }
    const fullText = lines.join("\n");
    console.debug(fullText);
    try {
      const logPath = ".xgkb-sync-debug.log";
      const existing = this.plugin.app.vault.getAbstractFileByPath(logPath);
      if (existing)
        await this.plugin.app.fileManager.trashFile(existing);
      await this.plugin.app.vault.create(logPath, fullText);
    } catch (e) {
    }
    new import_obsidian2.Notice("\u8BCA\u65AD\u5B8C\u6210\uFF0C\u8BE6\u60C5\u89C1\u63A7\u5236\u53F0\u548C .xgkb-sync-debug.log", 5e3);
  }
};

// src/syncEngine.ts
var SyncEngine = class {
  constructor(fsLocal, fsXgkb, db, settings) {
    this.progress = () => {
    };
    this.fsLocal = fsLocal;
    this.fsXgkb = fsXgkb;
    this.db = db;
    this.settings = { ...DEFAULT_SETTINGS, ...settings };
    this.stats = this.emptyStats();
  }
  emptyStats() {
    return { uploaded: 0, downloaded: 0, deleted: 0, skipped: 0, failed: 0, errors: [] };
  }
  /**
   * @param onProgress 进度回调
   * @param since      上次同步水位（毫秒时间戳）；首次同步不传
   */
  async runSync(onProgress, since) {
    var _a;
    this.stats = this.emptyStats();
    this.progress = onProgress || (() => {
    });
    const prog = (msg) => {
      console.debug(`[XGKB Sync] ${msg}`);
      this.progress(msg);
    };
    prog("\u8FDE\u63A5\u7384\u5173\u77E5\u8BC6\u5E93...");
    const initResult = await this.fsXgkb.init();
    if (!initResult.ok)
      throw new Error(`\u521D\u59CB\u5316\u5931\u8D25: ${initResult.error}`);
    prog("\u626B\u63CF\u672C\u5730\u6587\u4EF6...");
    const localFiles = this.fsLocal.listFiles();
    prog(`\u672C\u5730: ${localFiles.length} \u4E2A .md \u6587\u4EF6`);
    const { map: remoteMap, newSince } = await this.buildRemoteMap(since, prog);
    prog(`\u4E91\u7AEF: ${remoteMap.size} \u4E2A .md \u6587\u4EF6\uFF08\u6C34\u4F4D ${newSince}\uFF09`);
    this.stats.newSince = newSince;
    const localMap = /* @__PURE__ */ new Map();
    for (const f of localFiles)
      localMap.set(f.path, f);
    const allPaths = /* @__PURE__ */ new Set([...localMap.keys(), ...remoteMap.keys()]);
    prog(`\u5171 ${allPaths.size} \u4E2A\u8DEF\u5F84\u9700\u8981\u5904\u7406`);
    const plans = [];
    let idx = 0;
    for (const path of allPaths) {
      idx++;
      if (idx % 50 === 0 || idx === allPaths.size)
        prog(`\u51B3\u7B56\u4E2D ${idx}/${allPaths.size}...`);
      const local = localMap.get(path);
      const remote = remoteMap.get(path);
      const record = await this.db.get(path);
      const op = this.decide(path, local, remote, record);
      plans.push({ path, local, remote, record, op });
    }
    const downloadFileIds = [];
    for (const p of plans) {
      if (p.op === "download-new" || p.op === "download-update") {
        const id = (_a = p.remote) == null ? void 0 : _a.xgkbFileId;
        if (id)
          downloadFileIds.push(id);
      }
    }
    if (downloadFileIds.length > 0)
      prog(`\u6279\u91CF\u62C9\u53D6\u6B63\u6587 ${downloadFileIds.length} \u4E2A\u6587\u4EF6...`);
    const contentCache = await this.fsXgkb.readFilesBatch(downloadFileIds);
    idx = 0;
    for (const plan of plans) {
      idx++;
      if (idx % 50 === 0 || idx === plans.length)
        prog(`\u5904\u7406\u4E2D ${idx}/${plans.length}...`);
      await this.executePlan(plan, contentCache);
    }
    prog(`\u5B8C\u6210: \u2191${this.stats.uploaded} \u2193${this.stats.downloaded} \u2717${this.stats.deleted} \u2717fail:${this.stats.failed} \u2205${this.stats.skipped}`);
    return this.stats;
  }
  // ==================== 云端视图构建 ====================
  /**
   * 构建云端文件 Map，优先走增量路径，降级全量。
   */
  async buildRemoteMap(since, prog) {
    if (since !== void 0) {
      const sinceStr = new Date(since).toLocaleString("zh-CN");
      prog(`\u589E\u91CF\u6A21\u5F0F\uFF1Asince=${since} (${sinceStr})`);
      const result = await this.tryIncrementalRemoteMap(since, prog);
      if (result) {
        prog(`\u589E\u91CF\u6210\u529F\uFF1A\u4E91\u7AEF\u89C6\u56FE ${result.map.size} \u4E2A\u6587\u4EF6`);
        return result;
      }
      prog("\u589E\u91CF\u964D\u7EA7\uFF1A\u6267\u884C\u5168\u91CF\u626B\u63CF...");
    } else {
      prog("\u9996\u6B21\u540C\u6B65\uFF1A\u6267\u884C\u5168\u91CF\u626B\u63CF...");
    }
    return this.fullRemoteMap();
  }
  /**
   * 尝试增量路径：listChanges + batchGetMeta。
   * 遇到未知新文件（无本地记录）返回 null，由调用方降级全量。
   */
  async tryIncrementalRemoteMap(since, prog) {
    const safeSince = since - CHANGES_SAFETY_WINDOW_MS;
    const changesResult = await this.fsXgkb.listAllChanges(safeSince);
    if (!changesResult.ok) {
      console.warn("[XGKB Sync] listChanges \u5931\u8D25\uFF0C\u964D\u7EA7\u5168\u91CF:", changesResult.error);
      return null;
    }
    const { items, serverTime } = changesResult.value;
    const newSince = serverTime || Date.now();
    prog(`\u589E\u91CF\u53D8\u66F4: ${items.length} \u6761`);
    const upsertById = /* @__PURE__ */ new Map();
    const deleteIds = /* @__PURE__ */ new Set();
    for (const item of items) {
      const id = String(item.fileId);
      if (item.event === "delete")
        deleteIds.add(id);
      else
        upsertById.set(id, item);
    }
    const allRecords = await this.db.getAll();
    const fileIdToRecord = /* @__PURE__ */ new Map();
    for (const r of allRecords)
      fileIdToRecord.set(r.xgkbFileId, r);
    const knownUpsertIds = [];
    const unknownUpsertIds = [];
    for (const id of upsertById.keys()) {
      if (fileIdToRecord.has(id))
        knownUpsertIds.push(id);
      else
        unknownUpsertIds.push(id);
    }
    prog(`\u53D8\u66F4\u5206\u7C7B: upsert\u5DF2\u77E5=${knownUpsertIds.length} upsert\u65B0\u589E=${unknownUpsertIds.length} delete=${deleteIds.size}`);
    const folderIdToPath = /* @__PURE__ */ new Map();
    const rootId = this.fsXgkb.getRootId();
    if (rootId)
      folderIdToPath.set(rootId, "");
    for (const record of allRecords) {
      const parts = record.localPath.split("/");
      const folderPath = parts.length > 1 ? parts.slice(0, -1).join("/") : "";
      folderIdToPath.set(record.xgkbFolderId, folderPath);
    }
    const resolvedNewFiles = [];
    const unresolvedIds = [];
    for (const id of unknownUpsertIds) {
      const item = upsertById.get(id);
      const parentId = item.parentId != null ? String(item.parentId) : "";
      const folderPath = folderIdToPath.get(parentId);
      if (folderPath !== void 0) {
        const safeName = sanitizePathSegment(item.name || id);
        const filePath = folderPath ? `${folderPath}/${safeName}` : safeName;
        resolvedNewFiles.push({ id, path: filePath, item });
      } else {
        unresolvedIds.push(id);
      }
    }
    if (unresolvedIds.length > 0) {
      prog(`\u53D1\u73B0 ${unresolvedIds.length} \u4E2A\u6587\u4EF6\u4F4D\u4E8E\u5168\u65B0\u76EE\u5F55\uFF0C\u964D\u7EA7\u5168\u91CF\u5BF9\u8D26...`);
      return null;
    }
    if (resolvedNewFiles.length > 0) {
      prog(`\u8DEF\u5F84\u91CD\u5EFA\u6210\u529F ${resolvedNewFiles.length} \u4E2A\u65B0\u6587\u4EF6\uFF08\u65E0\u9700\u5168\u91CF\uFF09\uFF1A${resolvedNewFiles.map((f) => f.path).join(", ")}`);
    }
    const map = /* @__PURE__ */ new Map();
    for (const record of allRecords) {
      const id = record.xgkbFileId;
      if (deleteIds.has(id) || upsertById.has(id))
        continue;
      map.set(record.localPath, {
        path: record.localPath,
        name: record.localPath.split("/").pop() || record.localPath,
        mtime: record.remoteMtime,
        xgkbFileId: id,
        xgkbFolderId: record.xgkbFolderId
      });
    }
    if (knownUpsertIds.length > 0) {
      prog(`\u6279\u91CF\u83B7\u53D6 ${knownUpsertIds.length} \u4E2A\u53D8\u66F4\u6587\u4EF6\u5143\u6570\u636E...`);
      const metaMap = await this.fsXgkb.batchGetMetaAll(knownUpsertIds);
      for (const id of knownUpsertIds) {
        const meta = metaMap.get(id);
        const record = fileIdToRecord.get(id);
        if (!meta || meta.deleted)
          continue;
        map.set(record.localPath, {
          path: record.localPath,
          name: meta.name || record.localPath.split("/").pop() || record.localPath,
          mtime: meta.updateTime || record.remoteMtime,
          xgkbFileId: id,
          xgkbFolderId: meta.parentId != null ? String(meta.parentId) : record.xgkbFolderId
        });
      }
    }
    for (const { id, path, item } of resolvedNewFiles) {
      map.set(path, {
        path,
        name: item.name || path.split("/").pop() || path,
        mtime: item.updateTime || Date.now(),
        xgkbFileId: id,
        xgkbFolderId: item.parentId != null ? String(item.parentId) : ""
      });
    }
    return { map, newSince };
  }
  /** 全量扫描（listDescendantFiles 分页） */
  async fullRemoteMap() {
    const remoteResult = await this.fsXgkb.listFiles();
    if (!remoteResult.ok)
      throw new Error(`\u626B\u63CF\u4E91\u7AEF\u5931\u8D25: ${remoteResult.error}`);
    const map = /* @__PURE__ */ new Map();
    for (const f of remoteResult.value)
      map.set(f.path, f);
    const newSince = Date.now();
    console.debug(`[XGKB Sync] \u5168\u91CF\u626B\u63CF\u5B8C\u6210: ${map.size} \u4E2A\u6587\u4EF6\uFF0C\u65B0\u6C34\u4F4D=${newSince} (${new Date(newSince).toLocaleString("zh-CN")})`);
    return { map, newSince };
  }
  // ==================== 计划执行 ====================
  async executePlan(plan, contentCache) {
    const { path, local, remote, record, op } = plan;
    try {
      switch (op) {
        case "upload-new":
          await this.doUploadNew(path, local);
          break;
        case "upload-update":
          await this.doUploadUpdate(path, local, record);
          break;
        case "download-new":
          await this.doDownloadNew(path, remote, contentCache);
          break;
        case "download-update":
          await this.doDownloadUpdate(path, remote, record, contentCache);
          break;
        case "delete-local":
          await this.doDeleteLocal(path, record);
          break;
        case "delete-remote":
          await this.doDeleteRemote(record);
          break;
        case "skip":
          this.stats.skipped++;
          break;
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      this.stats.failed++;
      this.stats.errors.push(`${path}: ${msg}`);
      console.error(`[XGKB Sync] \u540C\u6B65\u5931\u8D25 ${path}:`, msg);
    }
  }
  // ==================== 决策逻辑 ====================
  decide(path, local, remote, record) {
    const dir = this.settings.syncDirection;
    if (!record) {
      if (local && !remote)
        return dir === "pull" ? "skip" : "upload-new";
      if (!local && remote)
        return dir === "push" ? "skip" : "download-new";
      if (local && remote) {
        if (dir === "pull")
          return "download-update";
        if (dir === "push")
          return "upload-update";
        return local.mtime >= remote.mtime ? "upload-update" : "download-update";
      }
      return "skip";
    }
    if (!local && !remote)
      return "skip";
    if (!local && remote) {
      if (dir === "push")
        return "skip";
      const remoteChanged = remote.mtime > record.remoteMtime + MTIME_TOLERANCE_MS;
      return remoteChanged ? "download-update" : "delete-remote";
    }
    if (local && !remote) {
      if (dir === "pull")
        return "skip";
      const localChanged = local.mtime > record.localMtime + MTIME_TOLERANCE_MS;
      return localChanged ? "upload-new" : "delete-local";
    }
    if (local && remote) {
      const localChanged = local.mtime > record.localMtime + MTIME_TOLERANCE_MS;
      const remoteChanged = remote.mtime > record.remoteMtime + MTIME_TOLERANCE_MS;
      if (!localChanged && !remoteChanged)
        return "skip";
      if (localChanged && !remoteChanged)
        return dir === "pull" ? "skip" : "upload-update";
      if (!localChanged && remoteChanged)
        return dir === "push" ? "skip" : "download-update";
      if (dir === "pull")
        return "download-update";
      if (dir === "push")
        return "upload-update";
      return local.mtime >= remote.mtime ? "upload-update" : "download-update";
    }
    return "skip";
  }
  // ==================== 操作执行 ====================
  async doUploadNew(path, local) {
    const content = await this.fsLocal.readFile(path);
    const result = await this.fsXgkb.createFile(path, content);
    if (!result.ok)
      throw new Error(`\u4E0A\u4F20\u5931\u8D25: ${result.error}`);
    await this.db.put({
      localPath: path,
      xgkbFileId: result.value.fileId,
      xgkbFolderId: result.value.folderId,
      localMtime: local.mtime,
      remoteMtime: Date.now(),
      syncStatus: "done",
      lastSyncAt: Date.now()
    });
    this.stats.uploaded++;
    this.progress(`\u2191 ${path}`);
  }
  async doUploadUpdate(path, local, record) {
    const content = await this.fsLocal.readFile(path);
    const fileName = path.split("/").pop() || path;
    const result = await this.fsXgkb.updateFile(record.xgkbFileId, fileName, content);
    if (!result.ok)
      throw new Error(`\u66F4\u65B0\u5931\u8D25: ${result.error}`);
    await this.db.put({
      ...record,
      localMtime: local.mtime,
      remoteMtime: Date.now(),
      syncStatus: "done",
      lastSyncAt: Date.now(),
      lastError: void 0
    });
    this.stats.uploaded++;
    this.progress(`\u2191 ${path}`);
  }
  async doDownloadNew(path, remote, contentCache) {
    const fid = remote.xgkbFileId;
    const body = contentCache.has(fid) ? contentCache.get(fid) : await this.fsXgkb.readFile(fid).then((r) => {
      if (!r.ok)
        throw new Error(`\u4E0B\u8F7D\u5931\u8D25: ${r.error}`);
      return r.value;
    });
    const actualMtime = await this.fsLocal.writeFile(path, body);
    await this.db.put({
      localPath: path,
      xgkbFileId: remote.xgkbFileId,
      xgkbFolderId: remote.xgkbFolderId || "",
      localMtime: actualMtime,
      remoteMtime: remote.mtime,
      syncStatus: "done",
      lastSyncAt: Date.now()
    });
    this.stats.downloaded++;
    this.progress(`\u2193 ${path}`);
  }
  async doDownloadUpdate(path, remote, record, contentCache) {
    const fid = remote.xgkbFileId;
    const body = contentCache.has(fid) ? contentCache.get(fid) : await this.fsXgkb.readFile(fid).then((r) => {
      if (!r.ok)
        throw new Error(`\u4E0B\u8F7D\u5931\u8D25: ${r.error}`);
      return r.value;
    });
    const actualMtime = await this.fsLocal.writeFile(path, body);
    await this.db.put({
      ...record,
      localMtime: actualMtime,
      remoteMtime: remote.mtime,
      syncStatus: "done",
      lastSyncAt: Date.now(),
      lastError: void 0
    });
    this.stats.downloaded++;
    this.progress(`\u2193 ${path}`);
  }
  async doDeleteLocal(path, record) {
    await this.fsLocal.trashFile(path);
    await this.db.delete(path);
    this.stats.deleted++;
    this.progress(`\u2717 \u672C\u5730\u5220\u9664 ${path}`);
  }
  async doDeleteRemote(record) {
    const result = await this.fsXgkb.deleteFile(record.xgkbFileId);
    if (!result.ok)
      throw new Error(`\u5220\u9664\u4E91\u7AEF\u5931\u8D25: ${result.error}`);
    await this.db.delete(record.localPath);
    this.stats.deleted++;
    this.progress(`\u2717 \u4E91\u7AEF\u5220\u9664 ${record.localPath}`);
  }
};

// src/syncStateDb.ts
function requestError(request) {
  var _a, _b;
  return new Error((_b = (_a = request.error) == null ? void 0 : _a.message) != null ? _b : "IndexedDB request failed");
}
var SyncStateDb = class {
  constructor() {
    this.db = null;
  }
  async open() {
    return new Promise((resolve) => {
      const request = indexedDB.open(DB_NAME, DB_VERSION);
      request.onupgradeneeded = () => {
        const db = request.result;
        if (!db.objectStoreNames.contains(DB_STORE_NAME)) {
          const store = db.createObjectStore(DB_STORE_NAME, { keyPath: "localPath" });
          store.createIndex("xgkbFileId", "xgkbFileId", { unique: false });
        }
      };
      request.onsuccess = () => {
        this.db = request.result;
        resolve({ ok: true, value: void 0 });
      };
      request.onerror = () => {
        var _a;
        resolve({ ok: false, error: `IndexedDB open failed: ${(_a = request.error) == null ? void 0 : _a.message}` });
      };
    });
  }
  close() {
    if (this.db) {
      this.db.close();
      this.db = null;
    }
  }
  async get(localPath) {
    if (!this.db)
      return void 0;
    return new Promise((resolve) => {
      const tx = this.db.transaction(DB_STORE_NAME, "readonly");
      const store = tx.objectStore(DB_STORE_NAME);
      const request = store.get(localPath);
      request.onsuccess = () => resolve(request.result || void 0);
      request.onerror = () => resolve(void 0);
    });
  }
  async getByXgkbFileId(xgkbFileId) {
    if (!this.db)
      return void 0;
    return new Promise((resolve) => {
      const tx = this.db.transaction(DB_STORE_NAME, "readonly");
      const store = tx.objectStore(DB_STORE_NAME);
      const index = store.index("xgkbFileId");
      const request = index.get(xgkbFileId);
      request.onsuccess = () => resolve(request.result || void 0);
      request.onerror = () => resolve(void 0);
    });
  }
  async put(record) {
    if (!this.db)
      return;
    return new Promise((resolve, reject) => {
      const tx = this.db.transaction(DB_STORE_NAME, "readwrite");
      const store = tx.objectStore(DB_STORE_NAME);
      const request = store.put(record);
      request.onsuccess = () => resolve();
      request.onerror = () => reject(requestError(request));
    });
  }
  async delete(localPath) {
    if (!this.db)
      return;
    return new Promise((resolve, reject) => {
      const tx = this.db.transaction(DB_STORE_NAME, "readwrite");
      const store = tx.objectStore(DB_STORE_NAME);
      const request = store.delete(localPath);
      request.onsuccess = () => resolve();
      request.onerror = () => reject(requestError(request));
    });
  }
  async getAll() {
    if (!this.db)
      return [];
    return new Promise((resolve) => {
      const tx = this.db.transaction(DB_STORE_NAME, "readonly");
      const store = tx.objectStore(DB_STORE_NAME);
      const request = store.getAll();
      request.onsuccess = () => resolve(request.result || []);
      request.onerror = () => resolve([]);
    });
  }
  async clear() {
    if (!this.db)
      return;
    return new Promise((resolve, reject) => {
      const tx = this.db.transaction(DB_STORE_NAME, "readwrite");
      const store = tx.objectStore(DB_STORE_NAME);
      const request = store.clear();
      request.onsuccess = () => resolve();
      request.onerror = () => reject(requestError(request));
    });
  }
};

// src/main.ts
var XgkbSyncPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    /** 防止并发执行多次同步 */
    this.isSyncing = false;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("refresh-cw", "Sync xgkb", async () => {
      await this.runSync();
    });
    this.addCommand({
      id: "xgkb-sync-now",
      name: "Sync now",
      callback: async () => {
        await this.runSync();
      }
    });
    this.addSettingTab(new XgkbPluginSettingTab(this.app, this));
    this.scheduleAutoSync();
  }
  /**
   * 注册/重置自动同步定时器。
   * 设置页修改间隔时调用，或插件加载时调用。
   * 使用 Plugin.registerInterval 确保插件卸载时自动清理。
   */
  scheduleAutoSync() {
    var _a;
    if (this.autoSyncHandle !== void 0) {
      window.clearInterval(this.autoSyncHandle);
      this.autoSyncHandle = void 0;
    }
    const intervalMin = (_a = this.settings.autoSyncInterval) != null ? _a : 0;
    if (intervalMin <= 0)
      return;
    const intervalMs = intervalMin * 60 * 1e3;
    this.autoSyncHandle = this.registerInterval(
      window.setInterval(() => {
        void this.runSync();
      }, intervalMs)
    );
    console.debug(`[XGKB Sync] \u81EA\u52A8\u540C\u6B65\u5DF2\u542F\u52A8\uFF0C\u95F4\u9694 ${intervalMin} \u5206\u949F`);
  }
  async loadSettings() {
    var _a;
    const raw = (_a = await this.loadData()) != null ? _a : {};
    const { lastSyncTime, ...rest } = raw;
    this.settings = Object.assign({}, DEFAULT_SETTINGS, rest);
    this.lastSyncTime = typeof lastSyncTime === "number" ? lastSyncTime : void 0;
  }
  async saveSettings() {
    await this.saveData({ ...this.settings, lastSyncTime: this.lastSyncTime });
  }
  async runSync() {
    var _a;
    if (!this.settings.appKey) {
      new import_obsidian3.Notice("Xgkb sync: configure app key first");
      return;
    }
    if (this.isSyncing) {
      console.debug("[XGKB Sync] \u4E0A\u6B21\u540C\u6B65\u4ECD\u5728\u8FDB\u884C\uFF0C\u8DF3\u8FC7\u672C\u6B21\u89E6\u53D1");
      return;
    }
    this.isSyncing = true;
    const isIncremental = this.lastSyncTime !== void 0;
    const sinceStr = this.lastSyncTime ? new Date(this.lastSyncTime).toLocaleString("zh-CN") : "\u65E0\uFF08\u9996\u6B21\u5168\u91CF\uFF09";
    console.debug(`[XGKB Sync] ===== \u5F00\u59CB\u540C\u6B65 mode=${isIncremental ? "\u589E\u91CF" : "\u5168\u91CF"} lastSyncTime=${(_a = this.lastSyncTime) != null ? _a : "-"} (${sinceStr}) =====`);
    new import_obsidian3.Notice(`XGKB Sync: \u5F00\u59CB${isIncremental ? "\u589E\u91CF" : "\u5168\u91CF"}\u540C\u6B65...`);
    const db = new SyncStateDb();
    let dbOpened = false;
    try {
      const dbResult = await db.open();
      if (!dbResult.ok) {
        new import_obsidian3.Notice(`XGKB Sync: \u6570\u636E\u5E93\u6253\u5F00\u5931\u8D25 - ${dbResult.error}`);
        return;
      }
      dbOpened = true;
      const api = new XgkbApi(this.settings.serverUrl, this.settings.appKey);
      const fsLocal = new FsLocal(this.app, this.settings.syncFolder);
      const fsXgkb = new FsXgkb(api, this.settings.targetFolderName);
      const engine = new SyncEngine(fsLocal, fsXgkb, db, this.settings);
      const stats = await engine.runSync(void 0, this.lastSyncTime);
      if (stats.newSince) {
        this.lastSyncTime = stats.newSince;
        await this.saveSettings();
        console.debug(`[XGKB Sync] \u6C34\u4F4D\u5DF2\u66F4\u65B0: ${stats.newSince} (${new Date(stats.newSince).toLocaleString("zh-CN")})`);
      }
      const lines = [];
      if (stats.uploaded > 0)
        lines.push(`\u2191${stats.uploaded}`);
      if (stats.downloaded > 0)
        lines.push(`\u2193${stats.downloaded}`);
      if (stats.deleted > 0)
        lines.push(`\u2717${stats.deleted}`);
      if (stats.failed > 0)
        lines.push(`\u5931\u8D25:${stats.failed}`);
      if (stats.skipped > 0)
        lines.push(`\u8DF3\u8FC7:${stats.skipped}`);
      const summary = lines.length > 0 ? lines.join(" ") : "\u65E0\u53D8\u5316";
      new import_obsidian3.Notice(`XGKB Sync \u5B8C\u6210: ${summary}`, stats.failed > 0 ? 8e3 : 4e3);
      if (stats.errors.length > 0) {
        console.error("[XGKB Sync] \u540C\u6B65\u9519\u8BEF:", stats.errors);
        new import_obsidian3.Notice(`XGKB Sync: ${stats.errors.length} \u4E2A\u6587\u4EF6\u540C\u6B65\u5931\u8D25\uFF0C\u8BF7\u67E5\u770B\u63A7\u5236\u53F0`, 8e3);
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error("[XGKB Sync] \u540C\u6B65\u5F02\u5E38:", msg);
      new import_obsidian3.Notice(`XGKB Sync \u540C\u6B65\u5931\u8D25: ${msg}`, 8e3);
    } finally {
      if (dbOpened)
        db.close();
      this.isSyncing = false;
    }
  }
};
